config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }
  resources :user
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  #used active storage for the profile picture
  has_one_attached :picture

  #custon fields added in devise and added the validation
  validates_presence_of     :name
  validates_presence_of     :address
  validates :phone,:presence => true, :numericality => true, :length => { :minimum => 10, :maximum => 15 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception

	
    before_action :configure_permitted_parameters, if: :devise_controller?
    

    #updated the params of the devose to register and to update the user details
    protected
    	def configure_permitted_parameters
	    	devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email, :password, :address, :phone,:picture])
	    	devise_parameter_sanitizer.permit(:account_update, keys: [:name, :email, :password, :address, :phone,:picture])
	  	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	#chech if user is adminor not if admin then get the all pther user details to show and to edit address
	#used only one template index to show all the users or the paricular users details
	def index
		if current_user && current_user.isadmin?
			@user=User.where(isadmin: false)
		end	
	end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  #to update the details of the user without enter password	
  protected
  def update_resource(resource, params)
    resource.update_without_password(params)
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  #controller to update each user data by admin

  #method to get the edit page details per user
	def edit
     @user = User.find(params[:id])
   end

   #method to to update user details
   def update
     @user = User.find(params[:id])
     if @user.update(user_params)
       redirect_to root_path
     else
       render json: @user, status: :error
     end
   end
   private
  
  #Params of the tabel user
  def user_params
    params.require(:user).permit(:name, :email, :address, :phone,:picture)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/registration_helper.rb
module RegistrationHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/home/index.html.erb
<div class="container">
  <% if user_signed_in? %>
    Logged in as <strong><%= current_user.email %></strong>.
    <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
    <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
    <% if current_user.isadmin?%>
    <table class="table table-bordered">
      <thead>
        <tr>
          <th>Image</th>
          <th>Name</th>
          <th>Phone</th>
          <th>Address</th>
          <th>Action</th>
        </tr>
      </thead>
      <tbody>
        <% @user.each do |userdetail| %>
      	<tr>
      	    <td><%= image_tag url_for(userdetail.picture), :style=>"width: 40px; height: 40px;"  if userdetail.picture.attached? %></td>
      	    <td><%= userdetail.name %></td>
      	    <td><%= userdetail.phone %></td>
      	    <td><%= userdetail.address %></td>
      	    <td><%= link_to "Edit", edit_user_path(userdetail) %></td>
      	</tr>
        <%end%>
      </tbody>
    </table>
    <%end%>
  <% else %>
    <nav class="navbar navbar-expand-sm bg-light">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "Sign up", new_user_registration_path, :class => 'nav-link'  %>
        </li>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, :class => 'nav-link'  %>
        </li>
      </ul>
    </nav>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SolbegTask</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
  <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %>
    <%= yield %>
  </body>
</html>

app/views/user/edit.html.erb
<!-- Edit each user by admin so created the contrelloer andthe view for that can't use the devose edit form -->
<div class="container">
<h2>Edit User</h2>

  <%= form_for(@user) do |f| %>
  <div class="form-group">
    <%= f.label :name %><br />
    <%= f.text_field :name, autofocus: true, :disabled => true %>
  </div>

  <div class="form-group">
    <%= f.label :address %><br />
    <%= f.text_field :address , :disabled => @user.isadmin==true %><!-- disabled when user is not admin -->
  </div>
  <% if @user.isadmin!=true%>
  <div class="form-group">
    <%= f.label :picture %><br />
    <%= f.file_field :picture %>
  </div>
  <%end%>
  <div class="form-group">
    <%= f.label :profile_picture %><br />
    <%= image_tag url_for(@user.picture), :style=>"width: 80px; height: 80px;"  if @user.picture.attached? %>
  </div> 
  <div class="form-group">
    <%= f.label :phone %><br />
    <%= f.text_field :phone, :disabled =>  @user.isadmin!=true %> <!-- disabled when user is admin -->
  </div>
  <div class="form-group">
    <%= f.label :email %><br />
    <%= f.email_field :email, :disabled => true %>
  </div>

  <div class="actions">
    <%= f.submit "Update", :class=>"btn btn-primary" %>
  </div>
<% end %>

<%= link_to "Back", :back %>
</div>